Repository AzarovRoman/Tests, pull requests merged in 2024-07, with the labels that each got.

#2 fix: сделал полукостыльный способ по изменению типа данных в таблице Question
  Tests.DAL/Context.cs
  Tests.DAL/Migrations/20240701162608_removed_difficulty.Designer.cs
  Tests.DAL/Migrations/20240701162608_removed_difficulty.cs
  Tests.DAL/Migrations/20240701162722_added_enum_difficulty.Designer.cs
  Tests.DAL/Migrations/20240701162722_added_enum_difficulty.cs
Labels: bug

#3 Featuretest 6( Я добавила метод получения вопроса по айди =* )
  Tests.BLL/Interfaces/IQuestionService.cs
  Tests.BLL/MapperProfiles/QuestionsMapper.cs
  Tests.BLL/Models/AnswerModel.cs
  Tests.BLL/Models/QuestionModel.cs
  Tests.BLL/Services/QuestionService.cs
  Tests.BLL/Tests.BLL.csproj
  Tests.DAL/Interfaces/IQuestionRepository.cs
  Tests.DAL/Repositories/QuestionRepository.cs
  Tests/Controllers/QuestionController.cs
  Tests/Extensions/ExtensionServiceProvider.cs
  Tests/Program.cs
  Tests/Tests.csproj
Labels: bug, enhancement, invalid

#4 Добавила метод для удаления вопроса по id =*
  Tests.BLL/Interfaces/IQuestionService.cs
  Tests.BLL/Services/QuestionService.cs
  Tests.DAL/Interfaces/IQuestionRepository.cs
  Tests.DAL/Repositories/QuestionRepository.cs
  Tests/Controllers/QuestionController.cs
Labels: enhancement

#6 Добавила метод получения рандомного вопроса из базы данных
  Tests.BLL/Interfaces/IQuestionService.cs
  Tests.BLL/Services/QuestionService.cs
  Tests.BLL/Tests.BLL.csproj
  Tests.DAL/Interfaces/IQuestionRepository.cs
  Tests.DAL/Repositories/QuestionRepository.cs
  Tests/Controllers/QuestionController.cs
Labels: enhancement

#7 Добавила индивидуальные модельки на создание вопроса ( без ID)
  Tests/Controllers/QuestionController.cs
  Tests/MapperAPIProfiles/QuestionAPIMapper.cs
  Tests/Models/AnswerAPIModel.cs
  Tests/Models/QuestionAPIModel.cs
Labels: enhancement
